# Ultimate Flipboard — APP core (nRF54H20 cpuapp)

CONFIG_PRINTK=y

CONFIG_LOG=y
CONFIG_LOG_PROCESS_THREAD_PRIORITY=-15
CONFIG_LOG_PROCESS_THREAD_CUSTOM_PRIORITY=y

# GPIO for button inputs
CONFIG_GPIO=y
